--- 
$schemaver: 1.1
name: test-repo-two
type: Web App
aliases:
short_description: Testing repo
assignment_group: gro:AD-Student Life Applications
notes: 
maintained_by:
  - ndpete
developed_by_byu: False
ddd:
  business_domain: 
  ubiquitous_language_url: 
  context_map_url: 
links:
  system_documentation_url: 
  source_repo_url: https://github.com/test-ndpete-org/test-repo-two
  swagger_urls:
microservice: False
technologies_used:
stages:
  development:
    urls:
      product_page: 
      physical_url: 
      virtual_url: 
    hosting_location: AWS
    aws_account: sla-dev-stg-ad-oit-byu
    relationships: 
      depends_on:
        db_read_write:
        db_read_only:
        software:
      supports:
        software:
        service:
      reverse_proxy: 
      runs_on:
        server_cluster:
          - <server cluster>
        virtual_server:
          - <virtual server>
        rack_server:
          - <rack server>
        blade_server:
          - <blade server>
tags:
  data-sensitivity: confidential
  env: development
  app: test-repo-two
  team: AD-Student Life Applications
federation_json_url: https://raw.githubusercontent.com/test-ndpete-org/test-repo-two/master/.repo-meta.yml
x-anything: