--- 
$schemaver: 1.1
name: test-repo-two
type: Background Process
aliases:
short_description: Testing repo
assignment_group: gro:AD-Back End Technologies and Applications
notes: 
maintained_by:
  - ndpete
developed_by_byu: False
ddd:
  business_domain: 
  ubiquitous_language_url: 
  context_map_url: 
links:
  system_documentation_url: google.com
  source_repo_url: https://github.com/test-ndpete-org/test-repo-two
  swagger_urls:
microservice: False
technologies_used:
stages:
  production:
    urls:
      product_page: 
      physical_url: 
      virtual_url: 
    hosting_location: BYU
    aws_account: 
    relationships: 
      depends_on:
        db_read_write:
          - fdcprd1
        db_read_only:
        software:
          - mavendeploy:production
      supports:
        software:
          - Call Managers:production
        service:
          - BYU Student Ratings
      reverse_proxy: morpheus
      runs_on:
        server_cluster:
          - autobaun
        virtual_server:
          - autobahn2
        rack_server:
          - Blade TAP02-HW
        blade_server:
          - esxi081
tags:
  data-sensitivity: internal
  env: production
  app: test-repo-two
  team: AD-Back End Technologies and Applications
federation_json_url: https://raw.githubusercontent.com/test-ndpete-org/test-repo-two/master/.repo-meta.yml
x-anything:

